"use strict";
let car = 'subaru';
console.log("Is car == 'subaru'? I predict True");
console.log(car == 'subaru');
console.log("Is car !== 'subaru'? I predict True");
console.log(car !== 'subaru');
console.log("Is car == 'ford'? I predict True");
console.log(car == 'ford');
console.log("Is car !== 'ford'? I predict True");
console.log(car !== 'ford');
console.log("Is car == 'suzuki'? I predict True");
console.log(car == 'suzuki');
console.log("Is car !== 'suzuki'? I predict True");
console.log(car !== 'suzuki');
console.log("Is car == 'toyota'? I predict True");
console.log(car == 'toyota');
console.log("Is car !== 'toyota'? I predict True");
console.log(car !== 'toyota');
console.log("Is car == 'BMW'? I predict True");
console.log(car == 'BMW');
console.log("Is car !== 'BMW'? I predict True");
console.log(car !== 'BMW');
